apiVersion: apps/v1
kind: Deployment
metadata:
  name: saapview-deployment

#ESPECIFICAÇÃO DAS REPLICAS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saapview-pod

  #ESPECIFICAÇÃO DO POD
  template:
    metadata:
      labels:
        app: saapview-pod
    spec:
      imagePullSecrets:
        - name: docker-registry-ssp
      containers:
        - name: saapview-container
          image: docker.ssp.go.gov.br/ssp/saapview:{{COMMIT_ID}}
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
