version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
            - APP_BASE_PACKAGE=${APP_BASE_PACKAGE}
            - PUBLIC_URL=${PUBLIC_URL}
